import React from 'react';
import type { Metadata } from 'next';
import { Space_Grotesk } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import UserProvider from '@/app/user-provider';
import { getCookie } from '@/utils/cookiesStorage';
import { tokenDecode } from '@/utils/tokenDecode';

const space_grotesk = Space_Grotesk({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
	title: 'Home | MY WEB BLOG',
	description: 'Generated by create next app',
};

export const revalidate = 0;

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const token = await getCookie('token');

	const getUser = () => {
		if (token?.value) {
			return tokenDecode(token.value);
		} else {
			return null;
		}
	};

	return (
		<html
			lang='en'
			className={`${space_grotesk.variable} scroll-smooth`}
			suppressHydrationWarning
		>
			<body className='bg-white text-black antialiased dark:bg-gray-950 dark:text-white'>
				<div className='flex h-screen flex-col justify-between'>
					<UserProvider defaultUser={getUser()}>
						<Header />
						<main className='mb-auto'>{children}</main>
					</UserProvider>
					<Footer />
				</div>
			</body>
		</html>
	);
}
