import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
	title: 'Blog | MY WEB BLOG',
	description: 'Generated by create next app',
};

export default function BlogLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className='flex flex-col items-center justify-between'>
			{children}
		</main>
	);
}
